import os
import time

os.system('chmod +x *')
os.system('clear')
os.system('figlet -f small Ddos Installing.. | lolcat')
print('[+] System Installing... ')
time.sleep(6)
os.system('chmod +x *')
os.system('cd && mv DDos-Attack $PREFIX/share')
os.system('cd $PREFIX/share/DDos-Attack && cp -r ddos unistall-ddos $PREFIX/bin')
time.sleep(5)
print('Setup Done')
print('Setup Done')
print('Setup Done')
print('Setup Done')
print('Setup Done')
print('Setup Done')
print('Setup Done')
print('[+] JUST TYPE ddos')
time.sleep(6)
os.system('ddos')
